version: '3.8'

services:
  drupal:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./drupal_event:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: drupal_db
      MYSQL_USER: drupal_user
      MYSQL_PASSWORD: drupal_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
